on:
    [push]

jobs:
    hello:
        runs-on: self-hosted
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Say hello
              run: node hello.js
